-- Teste de inserção de tenant com todos os campos
INSERT INTO tenants (
    name, 
    fantasy_name, 
    email, 
    cnpj, 
    phone, 
    address, 
    number, 
    complement, 
    neighborhood, 
    city, 
    state, 
    zip_code, 
    database_name, 
    status, 
    active, 
    plan_id, 
    plan_expires_at, 
    created_at, 
    updated_at
) VALUES (
    'Teste Empresa LTDA',
    'Teste Digital',
    'teste@empresa.com',
    '12345678000123',
    '11987654321',
    'Rua Teste',
    '123',
    'Sala 1',
    'Centro',
    'São Paulo',
    'SP',
    '01234567',
    'tenant_teste-empresa-ltda_abc123',
    'active',
    1,
    1,
    NULL,
    NOW(),
    NOW()
);
